
wandb:
  project: aefp
  entity: # TODO
  tags: [autoencoder, omega]
  mode: disabled

base:
  seed: null # assigns a random seed
  save_dir: /export01/data/omega/saved_models/aefp/autoencoder/
  save_filename: autoencoder_200.pt
  save_interval: 10
  test_interval: 1

model:
  encoder_only: false
  batch_size: 4
  num_epochs: 50
  lr: 3.0e-4 #4.5e-6
  params:
    embed_dim: 16
    
    ddconfig:
      double_z: True
      z_channels: 16
      in_channels: 1
      out_ch: 1
      ch: 32
      ch_mult: [2, 4, 8, 8]  # num_down = len(ch_mult)-1
      stride: [[2, 3], [2, 3], [2, 2], [2, 2]] #[[2, 3], [2, 3], [2, 2], [2, 2]]
      num_res_blocks: 4
      attn_levels: [2, 3, 4, 5]
      dropout: 0.1
      tanh_out: False
    
    lossconfig:
      loss_type: 'KLAELoss'
      params:
        kl_weight_start: 1.0e-8
        kl_weight_end: 1.0e-5
        kl_warmup_steps: 20000
        kl_warmup_start: 2000


dataset:
  name: omega
  contrastive: false

  folds: 0
  fold: 0
  folds_path: null

  data:
    data_path: /export01/data/omega
    data_modality: meg
    data_type: rest
    data_space: source_200

    block_shape: [200, 900]
    max_num_blocks: null

    sub_ids: 200
    val_percent: 0.05

    exclude_multiple_sessions: true

    device: cpu