
wandb:
  project: aefp
  entity: maxencelapatrie
  tags: [encoder, ts, lattice, omega]
  mode: online

base:
  seed: null # assigns a random seed
  save_dir: /export01/data/omega/saved_models/aefp/encoder/
  save_filename: encoder_200.pt
  save_interval: 1
  test_interval: 1

model:
  encoder_only: true
  batch_size: 4
  num_epochs: 10
  lr: 3.0e-4 #4.5e-6
  params:
    embed_dim: 16
    embed_shape: 20000
    
    ddconfig:
      double_z: false
      z_channels: 16
      in_channels: 1
      out_ch: 2
      ch: 32
      ch_mult: [2, 4, 8, 8]  # num_down = len(ch_mult)-1
      stride: [[2, 3], [2, 3], [2, 2], [2, 2]] #[[2, 3], [2, 3], [2, 2], [2, 2]]
      num_res_blocks: 4
      attn_levels: [2, 3, 4, 5]
      dropout: 0.1
      tanh_out: False
    
    lossconfig:
      loss_type: 'CELoss'
      params:
        margin: 0.5


dataset:
  name: omega
  contrastive: true

  folds: 0
  fold: 0
  folds_path: null

  data:
    data_path: /export01/data/omega
    data_modality: meg
    data_type: rest
    data_space: source_200

    block_shape: [200, 900]
    max_num_blocks: null

    sub_ids: 200
    val_percent: 0.05

    exclude_multiple_sessions: true

    device: cpu
  
  contrastive_params:
    positive_split: 0.5
    same_session: true
